---
- name: elasticsearch code signing key in place
  ansible.builtin.get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /etc/apt/trusted.gpg.d/elasticsearch.asc
- name: elasticsearch 7.x apt repository registered
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/elasticsearch.asc] https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
- name: elasticsearch installed
  ansible.builtin.apt:
    name: elasticsearch={{u22_elasticsearch7_version}}
    state: present
- name: elasticsearch config in place
  notify: restart elasticsearch
  ansible.builtin.template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: "0644"
- name: elasticsearch service enabled/running
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
